# Generated by Django 5.0.1 on 2024-01-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название компании"),
                ),
                (
                    "company_type",
                    models.IntegerField(
                        choices=[
                            (0, "Factory"),
                            (1, "Retail Network"),
                            (2, "Individual Entrepreneur"),
                        ],
                        verbose_name="тип компании",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="электронная почта компании",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=50, verbose_name="страна нахождения компании"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        max_length=50, verbose_name="город нахождения компании"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=100, verbose_name="улица нахождения компании"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        max_length=20, verbose_name="номер дома нахождения компании"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="задолженность перед поставщиком",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время создания записи"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="название продукта"),
                ),
                (
                    "model",
                    models.CharField(max_length=200, verbose_name="модель продукта"),
                ),
                (
                    "release_date",
                    models.DateField(verbose_name="дата выхода продукта на рынок"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="company.company",
                    ),
                ),
            ],
        ),
    ]
